version: '3.1'

services:
  chatroom.web:
    environment:
      - ASPNETCORE_URLS=http://+:80
    build:
      context: ./ChatRoom.Web
      dockerfile: Dockerfile
      args:
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Debug}
    ports:
      - "80:80"

  chatroom.db:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Test123!
    ports:
      - "1438:1433"
    volumes:
      - //e/nauka/chatroom_data:/var/opt/mssql