version: '3.1'

services:
  chatroom.web:
    image: chatroom.web
    depends_on:
      - chatroom.db
    networks: 
      - frontend
      - backend

  chatroom.db:
    image: microsoft/mssql-server-linux
    networks:
      - backend

networks:
  backend:
  frontend: